spring.application.name=spring-batch-demo
spring.batch.jdbc.initialize-schema=always
spring.batch.job.name=importCustomersJob
spring.batch.job.enabled=false
spring.sql.init.mode=always
spring.main.banner-mode=off
logging.level.org.springframework.batch=INFO
app.batch.cron=0/5 * * * * *

